### ISSUE TITLE
Erase does not work

### ISSUE THREAD

**Issue by fedorov** [fedorov/PCampReview#103]
To reproduce create structure, paint, select eraser, try erasing

**Comment by che85** [comment]
Works with my version of Slicer nightly build Nov 23 2015.

I will try the most recent nightly build

**Comment by fedorov** [comment]
yes, that's what we tried today. Fiona was working with an existing dataset, and she wanted to erase on a new structure she added to the existing ones.

**Comment by che85** [comment]
to reproduce this: 
1. use the WindowLevelEffect tool
2. select an already created label
3. select eraser (WindowLevelEffect button is still selected) - erasing does not work

When the WindowLevelEffect button is checked and selecting another effect button, the WindowLevelEffect button is automatically unchecked. The only exception is the EraseLabel button. With selecting the EraseLabel button, the WindowLevelEffect button and the EraseLabel button are checked at the same time. 

I guess that there is something wrong with the Eraser....

**Comment by fedorov** [comment]
When I observed this yesterday with Fiona, I did switch to Paint mode from WindowLevelEffect, and after that to Erase, and it did not work. Unless I am mistaken.

**Comment by che85** [comment]
I cannot reproduce it that way. It works for me. 

Confusing to me seems, that the user is always able to check the EraseLabel button even during the use of tools where erasing makes no sense.

**Comment by fedorov** [comment]
> Confusing to me seems, that the user is always able to check the EraseLabel button even during the use of tools where erasing makes no sense.

I agree, and I think we talked with @pieper about this - this was Steve's design decision.

**Comment by pieper** [comment]
It's just not something that seems important enough to change.  If you wanted to an Effect could have a property stating whether erasing should be enabled or not and that could be used to set the enable state of the erase button.

**Comment by fedorov** [comment]
It definitely confuses users! But considering the new generation of Editor is coming from the Segmentations project, it may not worth the effort to change the current Editor at this point.

@che85 independently from the Segmentations Editor, considering the usage scenarios of mpReview, we can completely hide the Editor toolbox panel, and toggle between windowlevel/pencil/erase modes with just few buttons, triggering Editor logic programmatically. I think our philosophy should be to give basic tools that are easy to use and that work, and think about adding more complicated tools if/when requested by the use cases. So far pencil, erase and W/L seem to be all we need.

**Comment by che85** [comment]
@fedorov: Only creating the buttons for our case would mean a lot of "hacking. For instance while using the "paint" tool you also want to see the label color, undo, redo and probably the label value, and the radius which is offered by the editor with predefined px radius buttons. Using our "own" buttons would not really solve the problem, i guess. It would make it worse ...? And what, if the Editor module changes? We are kind of depend to that and need to change our code again then.

@pieper @fedorov: 
My proposed solution would be: 
Developers should have some more flexibility for such cases. For instance if the developer only wants the paint and erasing tools (including undo/redo and radius buttons), there should be the possibility to create the Editor by choosing which tools should be available to the user. 

Two advantages would be given: 
1. easier development (less hacking like finding children etc. and hiding unwanted buttons/elements) and 2. simpler user interface which gives the user as much power as he/she needs which is also less confusing. 

If you want, I could take a look into that next month.

**Comment by fedorov** [comment]
@che85 we have colors and labels in the structure box already, no need to duplicate in the edit box, and we don't need paintbrush radius for the pencil tool. But yes, undo/redo is very helpful, and definitely fixing it properly in the editor would be ideal, I just don't know what is the effort needed to do that without breaking other things. Earlier attempts to fix the architecture that took place before (e.g., https://github.com/Slicer/Slicer/pull/287) had to be considered in the context that @pieper is the only person who knows all ins and outs of the Editor, and unless he is doing the changes, maintenance can become tricky.

We did not discuss this, but there is a plan to create a new generation Editor that is more flexible, and this is a good time to rethink the architecture and do these improvements in that next generation instead. @cpinter is leading that effort, and this will be a good opportunity to address issues like this one at the project week, so let's plan for that.

**Comment by cpinter** [comment]
@che85 I made some progress at the project week about the new Editor widget, see
http://www.na-mic.org/Wiki/index.php/2016_Winter_Project_Week/Projects/SegmentationEditorWidget
I will create a Labs page and post an update to the mailing list when we have a concrete design and a simple prototype. I made a note about being able to define a subset of effects, and we will incorporate it in the plans. If there are any wishlist items, please let me know!
About this particular issue in the current Editor, I agree with @pieper that fixing it might not be worth the invested time, especially considering the fragile nature of the module.

**Comment by fedorov** [comment]
As a followup, we advised the user to restart Slicer when this issue occurs, and that "fixed" the issue.
