### ISSUE TITLE
Module panel is too wide

### ISSUE THREAD

**Issue by fedorov** [fedorov/PCampReview#104]
Unfortunately, it appears that the width is set to the maximum width, which is the Structures widget in the Editor module. On 15-inch mac retina screen, module panel steals over 50% of the screen width! 

The layout used there is QHBoxLayout, and it keeps getting wider with the recent modifications of the functinality. I guess it would be great not to use QHBoxLayout in this part of Editor, or use combination of icons and tooltips instead of long button labels. @pieper any other suggestions?

Sceenshot below is full width of 15-inch mac screen.

![image](https://cloud.githubusercontent.com/assets/313942/11883071/6392dcd6-a4de-11e5-9b59-18fee01907b0.png)

**Comment by pieper** [comment]
At one point I recall hearing that there might be a Qt standard way of defining when a string was too long for the geometry hints and auto sizing it.  But when I went to implement this in the DataProbe I could not find that feature so I implemented this heuristic [1].  Would be nice to find a good general solution (if possible) or at least move this function to someplace where it could be used generally.  

[1] https://github.com/Slicer/Slicer/blob/e8a2e18e6edd85f7ff4ac0a6a37f3ed9fc7bf784/Modules/Scripted/DataProbe/DataProbe.py#L108

**Comment by che85** [comment]
@fedorov We could also just delete "Structure" from all buttons. Since those buttons are placed below "Per-Structure Volumes" it should be clear, that "add", "delete" and "propagate" are related to structures.

**Comment by fedorov** [comment]
is being addressed in #106 by removing unneeded buttons
