### ISSUE TITLE
Improve User Experience 

### ISSUE THREAD

**Issue by che85** [fedorov/PCampReview#106]
I think we should talk about usability aspects.

Some proposed improvements:
1. Having only one tab for "data selection". The current approach is a waste of space and the user needs to interact more than needed. I would leave the first tab like it is and add another splitview below the study selection list view.
2. Simplifying the segmentation tab. I got the feeling that the segmentation tab is far too full. The fiducials table somehow is lost in that layout when you don't know about that (unexperienced users)

@fedorov @rweiss42 What do you think?

**Comment by fedorov** [comment]
Yes, let's talk about this next time we meet. I agree it needs improvement!

Also, @rweiss42 is no longer working on this project (he moved on to another job), so don't expect to hear from him.

**Comment by fedorov** [comment]
> Also, @rweiss42 is no longer working on this project

I forgot to include "unfortunately" - it is unfortunate @rweiss42 is no longer working on this project!

**Comment by fedorov** [comment]
food for thought: https://www.smashingmagazine.com/2016/01/nobody-wants-use-your-product/

Not saying this is to be followed to the letter, but just a point of view to consider.

**Comment by fedorov** [comment]
another fun but sobering read on the topic: http://www.joelonsoftware.com/uibook/chapters/fog0000000062.html

**Comment by che85** [comment]
1. Truncating paths and showing full paths in tooltips
2. Move series selection to first tab
3. remove buttons "Export DICOM SEG", "Delete Structure" "Propagate Structure", "Make", "Hide"

**Comment by che85** [comment]
@fedorov Do we still need the functionality for propagating, making models or hiding models? I am hiding those buttons, but if we don't need the functionality I rather would delete them including the methods that are called when pushing one of them.

**Comment by che85** [comment]
@fedorov Even after deleting those buttons, the main UI width stays pretty wide. This is caused by the available effects. Do we need all of them?

![image](https://cloud.githubusercontent.com/assets/10195822/13433078/4b843d74-df9e-11e5-9f47-de6f4ee331a8.png)

**Comment by fedorov** [comment]
![4b843d74-df9e-11e5-9f47-de6f4ee331a8](https://cloud.githubusercontent.com/assets/313942/13433588/7dc21e6c-dfa0-11e5-9d47-388a9c70aaa3.png)

**Comment by fedorov** [comment]
Maybe add somewhere "Advanced" checkbox to bring those buttons back if needed?
