### ISSUE TITLE
Series selection widget height is a lot bigger than it should be after going back from segmentation step

### ISSUE THREAD

**Issue by che85** [fedorov/PCampReview#115]
To reproduce:
1. select study
2. go to segmentation tab
3. open collapsed buttons (so that the UI height exceeds the display)
4. go back to data selection tab

![image](https://cloud.githubusercontent.com/assets/10195822/13470054/32052720-e078-11e5-8cc0-d52ce4dcbebf.png)

**Comment by fedorov** [comment]
To clarify, I don't think the empty space is a big problem in itself. It is a bit unintuitive that buttons are in the bottom, and that's why I suggested to have a checkbox on top to select unselect all, as done in file save dialog. 

In either case, this is a minor issue.

**Comment by che85** [comment]
wontfix for now
