### ISSUE TITLE
Module does not work in developer mode

### ISSUE THREAD

**Issue by fedorov** [fedorov/PCampReview#147]
![image](https://cloud.githubusercontent.com/assets/313942/20718804/8be0c2e0-b61f-11e6-9a4b-de3018d95a55.png)

**Comment by fedorov** [comment]
doesn't work in non-developer mode either :-((

![image](https://cloud.githubusercontent.com/assets/313942/20718860/ba2c98c2-b61f-11e6-9c4d-4dfc2b9502e2.png)

**Comment by che85** [comment]
Oh yeah that makes sense. We really need to talk about having UI elements available to inheriting/using classes sod that we can avoid searching for elements. Or we need to make it more tolerant to not finding them...
