### ISSUE TITLE
Profile mpReviewPreprocessor

### ISSUE THREAD

**Issue by fedorov** [fedorov/PCampReview#161]

**Comment by che85** [comment]
Most time is consumed by the conversion process (directory creation, plugin selection, loadable by confidence, dcm2xml)

I can take a look at doing that parallel which might save time

Consumed time for our SliceTracker example dataset (preop):
Import: ~ 20 seconds
Conversion: ~ 160 seconds

**Comment by che85** [comment]
P.S. Import could actually be much faster when we prevent using the progress dialog:

With dialog: ~ 20 seconds
Without dialog: ~2 seconds

Obviously the callback for updating the progressbar is called as many times as the ctk.ctkDICOMIndexer() updates its progress

**Comment by fedorov** [comment]
Very helpful! Can you drill into 160?

**Comment by che85** [comment]
As discussed with @fedorov earlier most time is spend on the AX Dynamic series for both examine and conversion.
