### ISSUE TITLE
Support segmentation of overlapping structures

### ISSUE THREAD

**Issue by fedorov** [fedorov/PCampReview#5]
We can probably use the Editor "split merge" feature here -- include the merge frame in the GUI and integrate with the logic. When reporting form is invoked, populate with the label ID for the active label in Editor to link finding reporting.

![image](https://cloud.githubusercontent.com/assets/313942/6495054/8b600bc6-c294-11e4-96cb-5acc2e20f399.png)

**Comment by fedorov** [comment]
For visualization, generate surface models with no smoothing and enable slice intersections.

**Comment by mehrtash** [comment]
@fedorov I think you can close this issue.

**Comment by fedorov** [comment]
@mehrtash model intersections should show up only for the selected reference image. ie, if I am segmenting T2 and enable structure models, I should not be seeing structure models for ADC. The reason is segmentation of one sequence should not be affected by other segmentations. It looks like right now all structures are shown.

**Comment by fedorov** [comment]
Alireza, it looks like it still builds models for all labels, not only those for the selected reference - here's a screenshot. Is this the expected behavior, or you have not finished working on this issue?

![image](https://cloud.githubusercontent.com/assets/313942/7263623/305ee89a-e851-11e4-96f1-35de1ccc643f.png)

**Comment by fedorov** [comment]
Ah! I see I have not merged your pull request, and now there's a conflict because I merged others ... sorry for the confusion - ignore the previous comment.
