### ISSUE TITLE
Investigate replacement of collapsible buttons with tabs for workflow steps

### ISSUE THREAD

**Issue by fedorov** [fedorov/PCampReview#51]

**Comment by fedorov** [comment]
@rweiss42 sorry for this - Christian is a new member of the team, and I did not educate him on the proper procedures for committing new code! I did not expect he is so fast!

I will revert this change, and we will go over the proper workflow and give you time to review the changes.

Sorry, it's all my fault!

**Comment by che85** [comment]
I think that issue can be closed?

**Comment by fedorov** [comment]
yes! Fixed in #56
