### ISSUE TITLE
Refactor the code

### ISSUE THREAD

**Issue by fedorov** [fedorov/PCampReview#54]
Simplify/clean up the code without changing any of the functionality.

**Comment by rweiss42** [comment]
while we're at it, should also make sure the reload function works

**Comment by fedorov** [comment]
Yes, agree! Please put here any other issues that are related to this issue.

I think the first step is to just to clean up the code, then revisit data structures, then (in a separate issue) revisit GUI to use tabs (there's already an issue for that). @rweiss42 do you like the idea of tabs vs collapsible buttons in principle?

**Comment by rweiss42** [comment]
Sounds good.

Yes, I think using tabs would be a good idea.  It will give us more real estate to work with.

**Comment by che85** [comment]
Reopening: Refactoring code last till the project is finished.

**Comment by fedorov** [comment]
I think it is fair to say it is sufficiently refactored ....
