### ISSUE TITLE
Increase size of QListView's to take advantage of extra space

### ISSUE THREAD

**Issue by rweiss42** [fedorov/PCampReview#65]
We have a lot more vertical space now that we are using tabs.  We should take advantage of this by increasing the vertical size of the tables.

![screen shot 2015-06-26 at 12 19 09 pm](https://cloud.githubusercontent.com/assets/9009739/8383202/fb1e0e32-1bfd-11e5-981f-5c85ce491bdb.png)

**Comment by che85** [comment]
Should be fixed.
