### ISSUE TITLE
Add labels to the segmentation step to indicate what data you are working with

### ISSUE THREAD

**Issue by rweiss42** [fedorov/PCampReview#73]
In the old UI layout, we could see the titles of the previous steps which would show the user what data directory they're in and what patient/study was selected.  I'd like to add some labels (or something else?  suggestions?) either globally or just in step 4 to show that data directory you are in and what study you're currently working with.  Similar to how we added a label in step 2 to show what data directory you are currently in.

**Comment by fedorov** [comment]
yes, this will be helpful. I would add a small info panel above the tabs to provide information on the patient. We can also show content from DICOM about patient birth date, study date, whatever makes sense.

**Comment by che85** [comment]
@fedorov We are currently displaying to the user: selected "Study ID" and current "Data directory".
Do we need anything else? Otherwise I would close this issue.

**Comment by fedorov** [comment]
I would also add the reader ID, at the top

**Comment by fedorov** [comment]
Maybe also add patient ID, birth date and study date?
