### ISSUE TITLE
Add save capability to showExitStep4Or5Warning()

### ISSUE THREAD

**Issue by rweiss42** [fedorov/PCampReview#74]
When you're warned that you're going to loose any unsaved contours on leaving step4 or 5, can we add a button to the warning pop up that calls the save method?  Otherwise you have to go to completion step and click save there.

Better yet, track if things have changed since last save and only warn the user if in fact they're about to lose something.  But that sounds complicated...

**Comment by fedorov** [comment]
yes, good idea

**Comment by che85** [comment]
Should be fixed.

**Comment by rweiss42** [comment]
Seems to work for me.

**Comment by rweiss42** [comment]
Do we think the button text makes enough sense or does it make sense to change the text on the buttons?

OK = Exit, discard changes
Save = Save changes
Cancel = Cancel

**Comment by che85** [comment]
Sure I also could change that. I also thought about that.

**Comment by rweiss42** [comment]
Maybe just replicate the exit message that slicer puts up when you close the programs:

"Data has been modified.  Do you want to save them before exit? Save, Exit (Discard Modifications), Cancel Exit"

**Comment by che85** [comment]
But actually we don't check if data has been modified, so i prefer https://github.com/fedorov/PCampReview/issues/74#issuecomment-119689640

**Comment by fedorov** [comment]
Yes, let's not create an impression we check for data modified!

**Comment by che85** [comment]
So now it should be fine.
