### ISSUE TITLE
Find a better name for this module!

### ISSUE THREAD

**Issue by fedorov** [fedorov/PCampReview#86]
PCampReview (Prostate CAncer Multi-Parametric REVIEW) was my idea, and I am no longer happy with it (it is too long, and confusing, and may be unnecessarily narrowing the scope).

How about just mpReview?

Any other ideas?

@rweiss42 @che85 @PeterBehringer your comments are welcome!

**Comment by che85** [comment]
maybe one of those:
- mpMRIProstateAnalysis
- mpProstateReview
- mpProstateAnalysis

**Comment by PeterBehringer** [comment]
are prostate images the only possible application? What I dont like about the term "review" is that it sounds very passive - although it is actually a very "active" module. What about mpSegmenter?

**Comment by fedorov** [comment]
I agree, taking out PCamp was in part motivated it is not only about prostate.

Review is a broad process that may include annotation and segmentation.

mpSegmenter is very limiting I think, because you don't really need to do segmentation, you can use it just to view images.

**Comment by fedorov** [comment]
Ok guys, I am going to make the executive decision and rename it to mpReview - I didn't see a better idea.

**Comment by fedorov** [comment]
I am also going to move it under SlicerProstate organization

**Comment by fedorov** [comment]
@rweiss42 @che85 the repository moved under SlicerProstate organization and was renamed to mpReview. Please update the remotes in your checkouts!

@rweiss42 please let me know what grants from your side I should acknowledge!

The idea is to have this module as a working extension before RSNA so we can demo it well if/when needed. Please let me know if you have any other concerns. For now, I am closing this issue.
